### ISSUE TITLE
CIS shown not entitled / available when actually entitled

### ISSUE THREAD

**Issue by cmars** [canonical/ubuntu-advantage-client#1085]
We've recently added CIS to Ubuntu Pro entitlements, but the client does not show CIS as entitled=yes and status is a long dash (—).

![Screenshot from 2020-06-05 14-36-48](https://user-images.githubusercontent.com/23741/83916250-74ef4100-a73a-11ea-9dcb-78505a16149b.png)

However, the actual contract has CIS entitled and available.

![Screenshot from 2020-06-05 14-36-18](https://user-images.githubusercontent.com/23741/83916707-432aaa00-a73b-11ea-9248-bc9d5ba085b5.png)
![Screenshot from 2020-06-05 14-36-36](https://user-images.githubusercontent.com/23741/83916847-8127ce00-a73b-11ea-8a57-2f8301121ee5.png)

**Comment by blackboxsw** [comment]
This is because uaclient has the service name hard-coded as ``cis-audit`` which doesn't match the backend reported service name ``cis``. This could be fixed with either a backend config service rename to `cis-audit` or a ua client frontend commit changing that hardcoded [CISEntitlement.name ](https://github.com/canonical/ubuntu-advantage-client/blob/master/uaclient/entitlements/cis.py#L7)to "cis"

**Comment by mitechie** [comment]
Given that CIS is a known thing and isn't a fast moving target I feel the naming issue is low risk. If we do need a second offering, it would be something less standard and having the standard be CIS with a followup (like fips and fips-updates) would be reasonable.

**Comment by kikoreis** [comment]
Hmmm. Isn't there at least two principal ways in which CIS was meant to be used -- one to just analyze and report, and one to actually apply changes?

**Comment by HoyluBert** [comment]
Is there a work around for how to enable cis-audit? I am currently using the Ubuntu Pro FIPS 18.04 LTS on Azure and would like to test this feature.
