### ISSUE TITLE
Enabling FIPS on Ubuntu Pro 18.04 in Azure changes the ssh host key

### ISSUE THREAD

**Issue by davecore82** [canonical/ubuntu-advantage-client#1177]
Enabling FIPS on Ubuntu Pro 18.04 in Azure seems to change the ssh host key of the instance.

I cannot reproduce this on Ubuntu Pro 16.04 in Azure.

I also cannot reproduce this on both Ubuntu Pro 16.04 and Ubuntu Pro 18.04 in AWS.

Steps to reproduce:

-Launch Ubuntu Pro 18.04 instance in Azure

```
sudo add-apt-repository ppa:canonical-server/ua-client-daily --yes
sudo apt install ubuntu-advantage-tools ubuntu-advantage-pro --yes
sudo ua disable livepatch
sudo ua enable fips --beta

KERNEL=gnulinux-4.15.0-1011-fips-advanced-f3b1f9ec-6c9d-4e76-adc4-17b250df8e24

sudo tee /etc/default/grub.d/99-fips.cfg << __EOF__
GRUB_DEFAULT="Advanced options for Ubuntu>$KERNEL"
GRUB_CMDLINE_LINUX_DEFAULT="\$GRUB_CMDLINE_LINUX_DEFAULT fips=1" 
__EOF__

sudo update-grub
sudo reboot
```

After rebooting, try to SSH to the instance:

```
$ ssh ubuntu@52.242.37.94

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:fusRdUpDjWGd2GhJMdl8XP3uR1wtTRrC9+khj72mlQU.
Please contact your system administrator.
Add correct host key in /home/davecore/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/davecore/.ssh/known_hosts:158
  remove with:
  ssh-keygen -f "/home/davecore/.ssh/known_hosts" -R "52.242.37.94"
ECDSA host key for 52.242.37.94 has changed and you have requested strict checking.
Host key verification failed.
```

**Comment by mitechie** [comment]
Thanks, I wonder if this is due to the fips certified openssh package or something that the ua client is doing itself. We'll try to narrow it down.

**Comment by mitechie** [comment]
Just to note, the ua client doesn't currently support flipping fips especially on pro instances (there's an Ubuntu Pro FIPS image to use) and so this is targetted toward release 26 which is intended to be the release that fully supports fips in the ua client across all platforms.

**Comment by blackboxsw** [comment]
This continues to be a problem on latest daily ua-client due to the custom CPC images which will invalidate(delete) the cloud-init datasource cache  obj.pkl across reboots which forces cc_ssh configuration to run "fresh" each system boot. Because of also changing the underlying kernel from linux-azure -> linux-azure-fips which alters the ssh and libssl behaviors I think we end up getting different ssh host keys generated across each reboot in this case. Needs a bit more investigation about how, and if, we should best address this

**Comment by blackboxsw** [comment]
Ok this is a bug specifically with Azure-only Datasource in cloud-init which doesn't take into account that linux kernels before 4.15 have uppercase UUID and anything later than that is lowercase. This causes cloud-init to view this boot into FIPS kernel as a new instance id because lowercase UUID != uppercase UUID. [LP: #1835584](https://bugs.launchpad.net/cloud-init/+bug/1835584)


[cloud-init PR #798](https://github.com/canonical/cloud-init/pull/798)  resolves this for Azure and we will track the release of that into Xenial and Bionic  in the next cloud-init SRU.
