### ISSUE TITLE
Livepatch fails to apply patch when machine is booted with secure boot

### ISSUE THREAD

**Issue by lucasmoura** [canonical/ubuntu-advantage-client#1228]
It seems that livepatch is failing to apply the kernel patches if the machine has been booted with `secure boot` enabled. On the uaclient perspective, we can enforce a `static_affordance` check to see if the system has `secure boot`  enabled, and if so, we could not allow livepatch to be enabled.

However, it that a scenario that we want to support ? Meaning, should we drop uaclient livepatch support for `secure boot` machines ?

**Comment by renanrodrigo** [comment]
For secure boot to work, the signing key for the livepatch module needs to be in place. From Bionic on, it is included in the Kernel so we don't need to care - we support it fine.
For Xenial (and Trusty maybe? Do people have secure boot Trusty machines??) the key needs to be imported and loaded by the MOK before boot time, so there is nothing that UA can do about it.

For our testing on Xenial, we are disabling secure boot.

The best effort we can have is to show the problem in the livepatch status, instead of putting it as `disabled` - we are tracking that in SC-1008.

This specific issue can be closed.
