### ISSUE TITLE
USN.release_packages contain a sparse set of binary package versions for a given source package

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1445]
Blocked on security response for incomplete USN.release_package data.
-------------------------------
USN-4754-1 is a case where only some of the binary packages built from python2.7 source package are listed.

On a trusty system with an affected libpython2.7 installed, USN.released_packages has no libpython2.7 binary version represented so UA client will have to make an assumption that the source package version listed is the minimal upgraded version required to "fix" libpython2.7

**Comment by blackboxsw** [comment]
https://github.com/canonical-web-and-design/ubuntu-com-security-api/issues/35

**Comment by stevebeattie** [comment]
Hi,

So this problem is a result of attempting to use data that is intended for a web presentation in a client tool. When preparing Ubuntu Security Notices the security team will often attempt to prune the list of binary packages included in the USN to the set that we believe were affected by the vulnerability and that subset is what is submitted to the web teams security/notices/ API. But running a system that has packages that have only been partially updated is neither a tested nor supported configuration.

In the security team's data set that is consumed by things like the tools that generate the USN OVAL information, we also hvae captured the entire list of binaries in addition to the reduced subset. We can probably modify our tools to submit the additional information to the web-team API, but they would (a) need to ingest it and (b) only present it when requested by the json api and not in the web presentation.

**Comment by blackboxsw** [comment]
Thanks @stevebeattie.

> But running a system that has packages that have only been partially updated is neither a tested nor supported configuration."
In the absence of this data, Is the thinking UA client should update all binary packages to the latest version in the event that any given binary of a source package is required for upgrade?

It feels a bit like we are going a half-measure toward trusting USN.release_packages data (because it includes information about universe package fixes which a CVE might not report). Yet, I'm uncertain about other aspects of data such as, complete binary package lists and complete "pocket/component" definitions for all UA-related services as well as pocket "security" vs. "updates".

**Comment by blackboxsw** [comment]
Currently, UA client will behave something like the following
```bash
USN-4754-1: Python vulnerabilities
https://ubuntu.com/security/notices/USN-4754-1
Related CVEs: CVE-2021-3177, CVE-2020-27619
Related USNs: USN-4754-2, USN-4754-2, USN-4754-4, USN-4754-4
2 affected packages are installed: python2.7, python3.4
(1/2) python2.7:
A fix is available in UA Apps.
Error: USN-4754-1.release_packages has no libpython2.7-minimal version.
Unable to determine required fix version.
```

**Comment by mitechie** [comment]
> In the security team's data set that is consumed by things like the tools that generate the USN OVAL information, we also hvae captured the entire list of binaries in addition to the reduced subset. We can probably modify our tools to submit the additional information to the web-team API, but they would (a) need to ingest it and (b) only present it when requested by the json api and not in the web presentation.

This seems like an ok way to go. The data can be in a different key vs the one currently used by the web API "release_packages_all" or something that could be bikeshed that the client could use when available vs the data in "release_packages"

**Comment by lucasmoura** [comment]
It seems this issue is already resolved.
If we identify that this is still affecting UA, we can reopen it
