### ISSUE TITLE
fix: validate and prompt if esm-infra/apps is disabled

### ISSUE THREAD

**Issue by blackboxsw** [canonical/ubuntu-advantage-client#1455]
ua fix checks whether a token is attached and prompts for such attach.

If a fix is required from esm-apps and that service is not enabled on an attached machine. UA client should prompt for that enablement.

Example interaction
```bash
root@dev-t:~# ua fix CVE-2020-28196
CVE-2020-28196: Kerberos vulnerability
https://ubuntu.com/security/CVE-2020-28196
Related USNs: USN-4635-1
1 affected package is installed: krb5
(1/1) krb5:
A fix is available in UA Infra.
The update is not yet installed.

The esm-infra service is disabled. Choose: [E]nable to install updates [C]ancel
> E
{ ua enable esm-infra }
{ apt update && apt install --only-upgrade -y krb5-locales }
✔ CVE-2020-28196 is resolved.
```

**Comment by mitechie** [comment]
We should follow the same process and output as if they were not attached and just pick up from there since the person is attached. I suppose if the user is in this specific situation we know they disabled the service since it would default to enabled otherwise. We should do a check that they're entitled to this function (esm or esm apps) and be accurate in the output we give them. 

Using the spec as an example

```
A fix is available in UA Apps: ESM.
The update is not installed because this system does not have UA Apps: ESM enabled. 
Choose: [E]nable UA Apps: ESM [C]ancel
> E
<ua enable esm-apps>
<output from the above...>
{sudo apt update && apt sudo apt-get install --only-upgrade aftpd}
Other updates are pending. To install them all: sudo apt upgrade
✔ USN-4540-1 is addressed.
```
