### ISSUE TITLE
apt-get advertisement breaking things

### ISSUE THREAD

**Issue by chbarts** [canonical/ubuntu-advantage-client#2288]
The advertisement printed by apt-get is breaking things.

https://forum.checkmk.com/t/mk-apt-and-latest-idea-from-ubuntu/34135

**Comment by renanrodrigo** [comment]
Hello, Chris
Thanks for reporting this issue.

On a first note, APT's output is intended to be human readable, and scripts should not parse it. APT provides a C++/Python library and those can be used to get information without relying on the messages printed on screen.

Regardless of that, we are aware that this change had more impact than expected, and we are working on minimizing this impact by:
1. Changing the position of the message to be at the end of the output, rather than in the middle as it is now, and
2. Providing a command, i.e. `pro config set apt_news=False`, to completely remove messages like this.

A fix is on the way, and this issue will be closed once it lands.

**Comment by renanrodrigo** [comment]
Status updates will be given in https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1992026

**Comment by orndorffgrant** [comment]
We'll also be limiting these kinds of messages to only appear when using the `apt` binary. So they won't appear when using the `apt-get` binary. Hopefully this fill fix the issue with checkmk

**Comment by orndorffgrant** [comment]
This kind of message is removed from `apt-get` output in the latest release: 27.11.3. I believe that should fix your issue @chbarts so I'll close this.

Please feel free to re-open if this doesn't fix the problems.
